version: '3.5'

services:
  bot:
    image: ghcr.io/wilsonthewolf/halloween-candy-db:latest
    container_name: hcdb
    volumes:
      - ./data:/app/data
    restart: on-failure:5
    stop_grace_period: 10s
    ports:
      - 3000:3000
